### ISSUE TITLE
[Bug] Download progress not shown for some cases.

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#1044]
**Describe the bug**

When starting the program on the left, there is a non-neglible download time, but no progress bar is shown.

Maybe because there is other Bluetooth stuff going on?

```
v3.3.0b4 (Pybricks Beta v2.2.0-beta.3) + experimental broadcast
```

https://user-images.githubusercontent.com/12326241/234221370-ff44f084-4b32-4191-b286-cbcfd2041122.mp4

**Comment by dlech** [comment]
The compiled program is only 484 bytes and fits in a single Bluetooth packet on SPIKE Prime, so there are no progress steps other than 0 and 100%. 

There is a small bug where action to tell 100% to show is not happening, but even after fixing that, visually it is not different because the transition to the next state after 100% happens so fast (after sending one more bluetooth message) there is usually no time to actually see it.
