### ISSUE TITLE
how install package and use that in micro python?

### ISSUE THREAD

**Issue by mzajkaniha** [pybricks/support#111]
how can install a package and use that in micro python?

i installed pip3 by ssh ev3dev with this code:
`sudo apt-get install python3-pip`
and then installed paho-mqtt  package by pip3 with this code:
`import paho.mqtt.client as mqtt`
now i want use this package in my code , but it shows this error after running code:
`ImportError: no module named 'paho'`

now this is my question :can i use the installed package in micropython? if yes , how?

**Comment by laurensvalk** [comment]
`python3-pip` installs packages for use with `python3`, not MicroPython/Pybricks. See some more details here: https://github.com/pybricks/support/issues/113

In general, you'll want to look for specific packages for MicroPython, not generic Python packages, because they may require Python features that MicroPython does not have.
