### ISSUE TITLE
[Bug] Fixing the list blocks

### ISSUE THREAD

**Issue by ggramlich** [pybricks/support#1440]
**Describe the bug**
In block coding: Trying to access a random element from list results in the error
`NameError: name 'random' isn't defined`

**To reproduce**
Setup a variable as list.
Try to get random item from list.

**Expected behavior**
It should get a random element from the list.

**Screenshots**
![image](https://github.com/pybricks/support/assets/69276/61b31fad-b5d3-4cd5-a328-0c245e66c702)

**Comment by laurensvalk** [comment]
The app currently includes the default list blocks from Blockly. I'd like to gracefully deprecate those and add list blocks that suit the rest of the Pybricks API quite well. Programs that already have them can keep using them.

Things I'd like to avoid in the new blocks:
- Empty non-value inputs. These should be editable fields
- Shape changing in the get (value shape) and remove (statement shape)
- Block modes that generate multiple lines of code with intermediate temporary values (e.g. _set_ random value)

----

The following is probably a bit cryptic. I'm mainly posting this as a to-do list for myself. I will add screenshots of the blocks for review for discussion, later.

The main goal is to keep the most useful functionality, while making the blocks a lot simpler to use.

----

The list itself could be pre-populated with variable names in a dropdown, or kept empty like we do in the unpack block.

Suggested value shaped block:
- no mode, so only "get" operation
- Options: first, last, index, or random (so drop the option `# from end`)

Suggested statement shaped block:
- Instead of a separate set and an insert at (#, first, last, etc) as it is now, use: append, prepend, set
- this is the statement shape, so this is where the remove option belongs

**Comment by laurensvalk** [comment]
For the setter, I opted for a single dropdown, instead of mixed, nested dropdowns.

So set, remove, and insert. Each with index, start, or end. We could even drop first/last, but then you'd have to remember that 0 is first and -1 is last.

------------

What do you think of this draft, @ggramlich?

![image](https://github.com/pybricks/support/assets/12326241/c1ce9986-5d55-4d5d-ab18-05690b9d0047)

**Comment by ggramlich** [comment]
@laurensvalk 
This looks good to me.
I would keep the first / last options.

Could you add a screenshot of the expanded combobox of the statement block?

**Comment by laurensvalk** [comment]
Thanks for looking at this! Yes, these do indeed include more detail, which is a Pybricks extension on blockly:

![image](https://github.com/pybricks/support/assets/12326241/e1c9c76d-6a75-40a0-a4cb-6f4e97acc67e)

![image](https://github.com/pybricks/support/assets/12326241/4ccf9871-60f4-408d-a44c-0187d5df8cda)

**Comment by laurensvalk** [comment]
This is now available to try out in the latest beta version.

![image](https://github.com/pybricks/support/assets/12326241/4cb871f5-a73a-4f99-8fb8-7474441ef8de)

![image](https://github.com/pybricks/support/assets/12326241/ea5940f6-79a3-47e2-9df7-f9644f500bcc)
