### ISSUE TITLE
Potential bug with use of comment blocks [Bug] 

### ISSUE THREAD

**Issue by MonongahelaCryptidCooperative** [pybricks/support#1560]
![pybricks error](https://github.com/pybricks/support/assets/132950066/0b492bfe-4ebb-4b5c-aa1f-aaf6505845af)
So I found out that if you put a comment block in an empty conditional (such as a elif of else: the default value of pass will not be placed. This obviously results in a syntax error. I have included a screenshot showing this (there is a comment but no "pass" created with from the block code. 

Not a huge deal and I figured out what was going on immediately but could be an issue for novice users.

**Comment by laurensvalk** [comment]
Total rookie mistake on my part! Thanks for catching this. Will be fixed soon.

**Comment by laurensvalk** [comment]
Let's see if we've now covered all cases:

![image](https://github.com/pybricks/support/assets/12326241/396b9126-c82f-4885-8955-fb471ff8a8d7)

![image](https://github.com/pybricks/support/assets/12326241/b7ce3ed3-7a61-478f-af8b-86653c64114e)

![image](https://github.com/pybricks/support/assets/12326241/7c82e75c-9073-4619-8fb5-d1a8433dfaca)

![image](https://github.com/pybricks/support/assets/12326241/155fc8d2-ce10-4652-8f0c-ef547f89c707)

![image](https://github.com/pybricks/support/assets/12326241/093dd6b0-aac6-4ca6-8ed4-1aed19558a23)


-----------------

This is still broken:

![image](https://github.com/pybricks/support/assets/12326241/baa4d08d-2619-4b4b-b374-90efefa7ee13)

**Comment by laurensvalk** [comment]
So a comment block (like any block) suppresses the normal generation of the `pass` keyword.

Instead of messing with that in every possible parent block, we can just add the `pass` back below the comment if:
- the comment block is the last in a stack &&
- there are no other types of block in the stack &&
- the comment isn't in a loop/function where we already add a loop trap (`wait(1)`) in multitask mode &&
- it isn't the main block in a synchronous program

**Comment by laurensvalk** [comment]
Fix released in 

![image](https://github.com/pybricks/support/assets/12326241/5af1d452-e7d7-4051-bac4-ce7c1dfb5096)
