### ISSUE TITLE
Block to Python Generator Multiplies Arguments in `multitask until` 

### ISSUE THREAD

**Issue by DrTom** [pybricks/support#1590]
The `multitask until` block creates a `subtask` function in the context of async code. When a single argument is reference inside, the `subtask` argument gets multiplied with the same name seemingly by the time the argument is  used inside.  

<img width="1540" alt="Screenshot 2024-04-07 at 10 22 54" src="https://github.com/pybricks/support/assets/526053/36938904-a74a-43ca-be94-74b28a42cf23">

**Comment by laurensvalk** [comment]
This is going to the top of things to fix for this week's release. Thanks!

**Comment by laurensvalk** [comment]
Aside from that bug, your program has another interesting aspect if you remove the 1000 ms wait.

That leaves the task empty, so it could be ignored, at least in the wait for all multitask case. But not in the `one task` case since it still has to win the "race" against the task that takes a nonzero amount of time to run. I'll fix that as well.

**Comment by laurensvalk** [comment]
Fixed in the latest beta release. Thanks again!

![image](https://github.com/pybricks/support/assets/12326241/7b6c7969-e969-494d-809f-d6ad75dfa4b7)
