### ISSUE TITLE
[Doc] Online Doc does not reflect some functions

### ISSUE THREAD

**Issue by falk12** [pybricks/support#405]
Could not find hub.system nor hub.button online, but in 
docs-pybricks-com-en-latest.pdf

**Comment by dlech** [comment]
When you say "online" do you mean at https://code.pybricks.com or https://docs.pybricks.com?

**Comment by falk12** [comment]
> When you say "online" do you mean at https://code.pybricks.com or https://docs.pybricks.com?

I meant https://code.pybricks.com

**Comment by dlech** [comment]
Got it. (Those docs are actually downloaded to your computer, so technically offline.) They only get updated when we release a new version of Pybricks Code.

**Comment by falk12** [comment]
I see, that explains, good to know.
THX

**Comment by laurensvalk** [comment]
Thanks for opening this issue. We can make this less confusing by making the `stable` docs the default, instead of the latest `master`.

The current [stable](https://docs.pybricks.com/en/stable/) version seems to be pegged at (the now outdated) 2.0, so we'll need to fix that first.

**Comment by laurensvalk** [comment]
It is now possible to pick a version at the bottom left:

![image](https://user-images.githubusercontent.com/12326241/127283039-f844b8e9-cfa6-4f0f-8a01-62bcab3ee4e1.png)

The default version will be `stable` (equal to the highest number) instead of `latest`.

Starting with the next release (`v3.1`), the "online" and "offline" docs will become consistent again.
