### ISSUE TITLE
#!/usr/bin/env pybricks-micropython returns error message in visual studio code

### ISSUE THREAD

**Issue by FinnThom** [pybricks/support#471]

**Comment by laurensvalk** [comment]
From the screenshot, it looks like Visual Studio Code is trying to run your script on your *computer* instead of on the *robot*. 

To find out why this happens, can you check which debug configuration is active? It should look like this:

![image](https://user-images.githubusercontent.com/12326241/132668869-470e2976-ba71-43a5-8983-b0fa0a65f6f7.png)

**Comment by FinnThom** [comment]
Thanks for the answer. I hope this is what you meant.

![image](https://user-images.githubusercontent.com/65400635/132676102-f2ae8719-987a-49f7-b07a-41c9561d5822.png)

**Comment by laurensvalk** [comment]
What happens if you go to the debug tab in the menu on the left and click on the green triangle?

![image](https://user-images.githubusercontent.com/12326241/132685936-d1a494c7-44d3-4775-8567-e380400ef9bc.png)

**Comment by FinnThom** [comment]
![image](https://user-images.githubusercontent.com/65400635/132686427-41d1f3ea-9425-4a84-90b5-1c08bd1c6c7f.png)
