### ISSUE TITLE
#!/usr/bin/env pybricks-micropython returns error message in VS Code

### ISSUE THREAD

**Issue by FinnThom** [pybricks/support#472]
I am trying to use Visual Studio Code to write python code for the Lego Mindstorms EV3.

I followed the [official guide](https://le-www-live-s.legocdn.com/sc/media/files/ev3-micropython/getting-started-with-micropython-v2_enau-0e0a84a90ce27550aa995395695e687d.pdf), though I already had VS Code. The EV3 micropython extension is installed and enabled. The EV3 is connected and the microSD card is inserted.

![image](https://user-images.githubusercontent.com/65400635/132668251-ff6548b0-0cef-4a41-960d-27cf9dac5f68.png)

**Comment by laurensvalk** [comment]
From the screenshot, it looks like Visual Studio Code is trying to run your script on your *computer* instead of on the *robot*. 

To find out why this happens, can you check which debug configuration is active? It should look like this:

![image](https://user-images.githubusercontent.com/12326241/132668869-470e2976-ba71-43a5-8983-b0fa0a65f6f7.png)

**Comment by dlech** [comment]
It looks like the discussion continued in #471, so we'll close this duplicate issue.
