### ISSUE TITLE
Firmware installation error "GATT operation failed for unknown reason."

### ISSUE THREAD

**Issue by mfasold** [pybricks/support#505]
Installing the firmware unfortunately fails after pairing with the Boost Move hub. I follow the instructions, and when I click "Pair" in the browser's Bluetooth dialog, after maybe 3 seconds there appears the error message "GATT operation failed for unknown reason." The move hub continues to be in firmware-flashing mode after that. Any help appreciated!

Environment: Lego Boost Hub. Google Chrome Browser (94.0.4606.81), MacBookPro 2015 (yes, has BLE) running Mac OS 11.6.

**Comment by dlech** [comment]
The light will turn off for a short time while the flash memory is being erased. This is usually when I release the button. 

Also see https://github.com/pybricks/support/discussions/270 if you continue to have problems.

**Comment by tanvirarafin** [comment]
Issue still persists for the movehub. Maybe the write operation is too fast for older boost hub. Can you help me is slowing down the firmware flashing process.

**Comment by tanvirarafin** [comment]
> Thanks for your help. I will see what further debugging will show. Currently I get an `checksum: got 0x0f expected 0x2c` error, but didn't had time to look further.
> Thanks a lot for this great project!

@cwrs Did you manage to solve the problem. I am having similar issues.

**Comment by dlech** [comment]
This issue was solved by https://github.com/pybricks/support/issues/505#issuecomment-939528098, so if you see the same error message but that does not fix the problem, then you likely have a different problem.  Any additional comments on this issue are likely to be forgotten since the issue has been closed.

Please start a new issue and provide the exact steps needed to reproduce the issue. Also see #270 for troubleshooting hints. Logging Bluetooth packets often provides insight into these sorts of issues.
