### ISSUE TITLE
[Bug] Pybricks Code beta does not work offline

### ISSUE THREAD

**Issue by laurensvalk** [pybricks/support#686]
**Describe the bug**

Our website seems to be down (main website and docs too). Pybricks Code continues to work, but Pybricks Code Beta does not.

![image](https://user-images.githubusercontent.com/12326241/179476724-4c56638e-8721-4d04-b2e4-86c9486f8822.png)

**Comment by dlech** [comment]
It works offline for me. It can be tested like this:

![image](https://user-images.githubusercontent.com/963645/179542089-a4a2d100-682a-4c93-bb53-5d2d55ea399a.png)

Then did CTRL+SHIFT+R and briefly saw "no internet" then the page loaded as expected.

The network tab also confirms that everything was loaded using the ServiceWorker as expected:

![image](https://user-images.githubusercontent.com/963645/179543134-0d549a09-1de8-4e19-b383-5f75d718865f.png)


It is possible that when the website went down, your local version of beta was not "ready for offline use"

![image](https://user-images.githubusercontent.com/963645/179542309-160e92be-2e99-43f7-b6a0-5938b8d880e5.png)

**Comment by dlech** [comment]
Looking at this again in light of #689, I now see that `main.[hash].js` is loaded from "(disk cache)" instead of "(ServiceWorkder)". This explains why it would work for me but not for Laurens.

This should be fixed in v3.2.0b3 (Pybricks Beta (Dev) v2.0.0-beta.5).

We can see that `main.[hash].py` is now served by the "(ServiceWorker)".

Fixed by https://github.com/pybricks/pybricks-code/commit/30314db086668980f552c977cd440ca8ce337538.
